### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'models/data/train.article.dict'

### ISSUE THREAD

**Issue by beyoung** [kiyukuta/lencon#3]
it would be many thanks if "train.article.dict" is commited with code.

**Comment by kiyukuta** [comment]
Do you already have [Annotated English Gigaword](https://catalog.ldc.upenn.edu/LDC2012T21) Corpus ?

If so, please follow this instruction and you can get the `train.article.dict` with other files such as `train.title.dict` or `train.article.txt` etc.
https://github.com/facebookarchive/NAMAS#generating-the-data

If you don't have the Gigaword corpus and  want to run on another corpus, you have to build your own dict file.
I will commit the sample of train, test, and dict file. please check it!

**Comment by beyoung** [comment]
Thanks for the detailed instruction.  Yeah , i don't have Gigaword corpus , i'm a fresher. So , i just want to run this project at this stage.  Many thanks if  you commit the sample of train, test, and dict file.

**Comment by kiyukuta** [comment]
I added an additional instruction about the data format with small sample.
https://github.com/kiyukuta/lencon/blob/master/README.md#preparing-your-own-dataset

Please ask me if you have any question!

**Comment by beyoung** [comment]
I am sorry, i didn't find  the sample of train, test, and dict file in your commit . And I when i open https://catalog.ldc.upenn.edu/LDC2003T11, it warns that "We're sorry, but something went wrong." So, i can't access the dataset,  and if i use anthoer dataset, what's the format of it?  And can you provider me a copy of your datasets? I just want to run this project as soon as possible. Thank again for your patiently answer.

**Comment by kiyukuta** [comment]
Sorry for late reply.

> i didn't find the sample of train, test, and dict file in your commit

yes, I added discription of them in README.md

> and if i use anthoer dataset, what's the format of it? 

I added the description of data format here for vocabularies (`train_article_dict`, `train_title_dict`) : 
https://github.com/kiyukuta/lencon/blob/master/README.md#vocabulary-list-src_vcb-and-trg_vcb

and source and target files:
https://github.com/kiyukuta/lencon/blob/master/README.md#source-and-target-file-train_src_file-train_trg_file-valid_src_file-and-valid_trg_file

vocabulary format: one words per line.
source (article) and target (title) file: one sentence per line.

> And can you provider me a copy of your datasets?

sorry, I cannot share the dataset for license reason.

**Comment by kiyukuta** [comment]
please tell me if you are still confused about data preparation.
then I will add the script which performs preprocessing to your data.

**Comment by beyoung** [comment]
@kiyukuta thanks anyway , It helps me a lot .  I'll follow your instruction and run this program again.  Thanks.  #@。@# .

**Comment by kiyukuta** [comment]
The important point is that to replace the paths in `models/XXX.ini` to the path of your original data.
please tell me if you are confused again. thanks!
